### ISSUE TITLE
dailyChargingCapacity unknown

### ISSUE THREAD

**Issue by tester277** [tomquist/hm2mqtt#428]
### Device Model

Jupiter C+

### Firmware Version

142.36.217.110

### Installation Method

Home Assistant

### Issue Description

after update to 1.10.0 dailyChargingCapacity is unknown 
Protokolldetails (WARNUNG)
Logger: homeassistant.helpers.template
Quelle: helpers/template/__init__.py:685
Erstmals aufgetreten: 17:18:01 (8 Vorkommnisse)
Zuletzt protokolliert: 17:21:40

Template variable warning: 'dict object' has no attribute 'dailyChargingCapacity' when rendering '{{ value_json.dailyChargingCapacity }}'
Thank You

### hm2mqtt Configuration

```text

```

### hm2mqtt Logs

```text
values":{"ele_d":"256","ele_m":"5180","ele_y":"50933","pv1_p":"0","pv1_s":"1","pv2_p":"0","pv2_s":"0","pv3_p":"0","pv3_s":"1","pv4_p":"0","pv4_s":"1","grd_o":"0","grd_t":"1","gct_s":"1","cel_s":"0","cel_p":"1024","cel_c":"100","err_t":"0","wor_m":"1","tim_0":"0|0|7|0|127|100|0","tim_1":"7|0|11|0|127|60|0","tim_2":"11|0|17|0|127|90|0","tim_3":"17|0|23|57|127|100|0","tim_4":"0|0|0|0|255|0|0","cts_m":"0","grd_d":"139","grd_m":"4457","dev_n":"142","dev_i":"110","dev_m":"217","dev_b":"36","dev_t":"111","wif_s":"63","ala_c":"0","ful_d":"0","ssid":"marsrelay","stop_s":"10","htt_p":"0","ct_t":"4","phase_t":"1","dchrg":"1","seq_s":"3","ctrl_r":"0","shelly_p":"1010","c_ratio":"100","b_lck":"0","dod":"88","bl":"1","total_b":"4","online_b":"15"},"dailyPowerGeneration":2.56,"monthlyChargingCapacity":51.8,"yearlyChargingCapacity":509.33,"pv1Power":0,"pv1Status":true,"pv2Power":0,"pv2Status":false,"pv3Power":0,"pv3Status":true,"pv4Power":0,"pv4Status":true,"dailyDischargeCapacity":1.39,"monthlyDischargeCapacity":44.57,"combinedPower":0,"workingStatus":1,"ctStatus":1,"batteryWorkingStatus":"keep","batteryEnergy":10.24,"batterySoc":100,"errorCode":0,"workingMode":"automatic","autoSwitchWorkingMode":0,"httpServerType":0,"wifiSignalStrength":-63,"ctType":4,"phaseType":1,"rechargeMode":"threePhase","deviceVersion":142,"bmsVersion":36,"mpptVersion":217,"inverterVersion":110,"screenVersion":111,"wifiName":"marsrelay","surplusFeedInEnabled":false,"depthOfDischarge":88,"alarmCode":0,"batteryPacks":4,"shellyPort":1010,"phaseDiagnosisStatus":3,"bluetoothAdvertisingEnabled":true,"timePeriods":
```

### Hame Relay Configuration

```text

```

### Hame Relay Logs

```text

```

**Comment by tomquist** [comment]
See #420 
That rename is intentional, see the *Changed* entry for 1.10.0 in the
[changelog](https://github.com/tomquist/hm2mqtt/blob/main/CHANGELOG.md): `ele_d` is
today's solar production, not energy charged into the battery, so the sensor is now
called *Daily Power Generation*.

If you had it on the Energy Dashboard, move it to *Solar production*.
